SM/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('student.urls')),
]

student/urls.py
from django.urls import path
from . import views
from student.views import*

app_name = 'student'
urlpatterns = [
    path('', views.index, name='index'),
    path('Login/', views.Login, name='Login'),
    path('Logout/', views.Logout, name='Logout'),
    path('add_stu/', views.add_stu, name='add_stu'),

    path('About/', views.About, name='About'),
    path('show_contact/', views.show_contact, name='show_contact'),

    path('add_stu1/', views.add_stu1, name='add_stu1'),

    path('masterDashboard/', views.masterDashboard, name='masterDashboard'),
    path('add_stu_save/', views.add_stu_save, name='add_stu_save'),

    path('add_stu1_save/', views.add_stu1_save, name='add_stu1_save'),

    path('edit_stu/^(?P<stu_id>\w+)/$', views.edit_stu, name='edit_stu'),
    path('stu_edit_save/^(?P<stu_id>\w+)/$', views.stu_edit_save, name='stu_edit_save'),
    path('del_stu/^(?P<stu_id>\w+)/$', views.del_stu, name='del_stu'),
    path('download/', views.download, name='download'),

]

templates/_messages.html
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
        {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}

templates/add_stu.html
<html>
{% load static %}
<head>
<title>Add_Student</title>
  <link rel="stylesheet" href={% static "css/student.css" %}>

</head>
<body>
<div class="container">
  <form method='post' action="{% url 'student:add_stu_save' %}" enctype="multipart/form-data">
  {% csrf_token %}
  <h3>STUDENT REGISTRATION FORM</h3>

  <table align="center" cellpadding="10">
        <!----- First Name ---------------------------------------------------------->
    <tr>
      <td>Enrollment No</td>
      <td><input type="text" name="stu_id" placeholder="Enter Enrollment No" maxlength="30" required />
        (max 30 characters a-z and A-Z)
      </td>
    </tr>

    <!----- First Name ---------------------------------------------------------->
    <tr>
      <td>FIRST NAME</td>
      <td><input type="text" name="stu_fname" placeholder="Enter First Name" maxlength="30" required  />
        (max 30 characters a-z and A-Z)
      </td>
    </tr>

    <!----- Last Name ---------------------------------------------------------->
    <tr>
      <td>LAST NAME</td>
      <td><input type="text" name="stu_lname" placeholder="Enter Last Name" maxlength="30" />
        (max 30 characters a-z and A-Z)
      </td>
    </tr>

    <!----- Date Of Birth -------------------------------------------------------->
    <tr>
      <td>DATE OF BIRTH</td>

      <td>
        <select name="stu_Day" id="Birthday_Day" required>
          <option value="00">Day:</option>
          <option value="1">1</option>
          <option value="2">2</option>
          <option value="3">3</option>

          <option value="4">4</option>
          <option value="5">5</option>
          <option value="6">6</option>
          <option value="7">7</option>
          <option value="8">8</option>
          <option value="9">9</option>
          <option value="10">10</option>
          <option value="11">11</option>
          <option value="12">12</option>

          <option value="13">13</option>
          <option value="14">14</option>
          <option value="15">15</option>
          <option value="16">16</option>
          <option value="17">17</option>
          <option value="18">18</option>
          <option value="19">19</option>
          <option value="20">20</option>
          <option value="21">21</option>

          <option value="22">22</option>
          <option value="23">23</option>
          <option value="24">24</option>
          <option value="25">25</option>
          <option value="26">26</option>
          <option value="27">27</option>
          <option value="28">28</option>
          <option value="29">29</option>
          <option value="30">30</option>

          <option value="31">31</option>
        </select>

        <select id="Birthday_Month" name="stu_Month" required>
          <option value="00" >Month:</option>
          <option value="January">Jan</option>
          <option value="February">Feb</option>
          <option value="March">Mar</option>
          <option value="April">Apr</option>
          <option value="May">May</option>
          <option value="June">Jun</option>
          <option value="July">Jul</option>
          <option value="August">Aug</option>
          <option value="September">Sep</option>
          <option value="October">Oct</option>
          <option value="November">Nov</option>
          <option value="December">Dec</option>
        </select>

        <select name="stu_Year" id="Birthday_Year" required>

          <option value="0000">Year:</option>
          <option value="2012">2012</option>
          <option value="2011">2011</option>
          <option value="2010">2010</option>
          <option value="2009">2009</option>
          <option value="2008">2008</option>
          <option value="2007">2007</option>
          <option value="2006">2006</option>
          <option value="2005">2005</option>
          <option value="2004">2004</option>
          <option value="2003">2003</option>
          <option value="2002">2002</option>
          <option value="2001">2001</option>
          <option value="2000">2000</option>

          <option value="1999">1999</option>
          <option value="1998">1998</option>
          <option value="1997">1997</option>
          <option value="1996">1996</option>
          <option value="1995">1995</option>
          <option value="1994">1994</option>
          <option value="1993">1993</option>
          <option value="1992">1992</option>
          <option value="1991">1991</option>
          <option value="1990">1990</option>

          <option value="1989">1989</option>
          <option value="1988">1988</option>
          <option value="1987">1987</option>
          <option value="1986">1986</option>
          <option value="1985">1985</option>
          <option value="1984">1984</option>
          <option value="1983">1983</option>
          <option value="1982">1982</option>
          <option value="1981">1981</option>
          <option value="1980">1980</option>
        </select>
      </td>
    </tr>
        <!----- Mobile Number ---------------------------------------------------------->
    <tr>
      <td>MOBILE NUMBER</td>
      <td>
        <input type="text" name="stu_contact" placeholder="Mobile Number" maxlength="10" required />
        (10 digit number)
      </td>
    </tr>

    <!----- Email Id ---------------------------------------------------------->
    <tr>
      <td>EMAIL ID</td>
      <td><input type="email" name="stu_email" placeholder="Enter Email Id" maxlength="100" required /></td>
    </tr>
    <!----- Room No ---------------------------------------------------------->
    <tr>
      <td>ROOM NO</td>
      <td><input type="text" name="stu_room" placeholder="Enter Room No" maxlength="50" required/></td>
    </tr>

    <!----- Gender ----------------------------------------------------------->
    <tr>
      <td>GENDER</td>
      <td>
        Male <input type="radio" name="stu_gender" value="Male" required/>
        Female <input type="radio" name="stu_gender" value="Female" />
      </td>
    </tr>

    <!----- Address ---------------------------------------------------------->
    <tr>
      <td>ADDRESS <br /><br /><br /></td>
      <td><textarea name="Address" placeholder="Enter Address" rows="4" cols="30" required></textarea></td>
    </tr>

    <!----- City ---------------------------------------------------------->
    <tr>
      <td>CITY</td>
      <td><input type="text" name="City" placeholder="Enter City" maxlength="30" required />
        (max 30 characters a-z and A-Z)
      </td>
    </tr>

    <!----- Pin Code ---------------------------------------------------------->
    <tr>
      <td>PIN CODE</td>
      <td><input type="text" name="Pin_Code" placeholder="Enter Pin Code" maxlength="6" required />
        (6 digit number)
      </td>
    </tr>

    <!----- State ---------------------------------------------------------->
    <tr>
      <td>STATE</td>
      <td><input type="text" name="State" placeholder="Enter State" maxlength="30" required/>
        (max 30 characters a-z and A-Z)
      </td>
    </tr>

    <!----- Country ---------------------------------------------------------->
    <tr>
      <td>COUNTRY</td>
      <td><input type="text" name="Country" placeholder="Enter Country" maxlength="15" required/></td>
    </tr>
    <!----- Course ---------------------------------------------------------->
    <tr>
      <td>COURSES</td>
         <td><input type="text" name="COURSES" placeholder="Enter Courses" required/></td>
    </tr>
    <tr>
      <!----- Branch ---------------------------------------------------------->
      <td>BRANCH</td>
         <td><input type="text" name="stu_branch" placeholder="Enter Branch"/></td>
    </tr>

    <!----- Submit and Reset ------------------------------------------------->
    <tr>
      <td colspan="2" align="center">
        <input type="submit" value="Submit">
        <input type="reset" value="Reset">
      </td>
    </tr>
  </table>

  </form>
</div>
</body>
</html>

templates/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<body>
    
    <!-- <table class="table">
        <thead>
          <tr>
            <th scope="col">S.No</th>
            <th scope="col">Name</th>
            <th scope="col">Mail</th>
            <th scope="col">Text</th>
          </tr>
        </thead>
        <tbody>
            {% for i in Alldata %}
          <tr>
            <th scope="row">{{i.id}}</th>
            <td>{{i.About_me_name}}</td>
            <td>{{i.About_me_mail}}</td>
            <td>{{i.About_me_text}}</td>

          </tr>
          {% endfor %}
        </tbody>
      </table> -->

<center>
{% for i in Alldata %}
<br>
      <input type="id" value="{{i.id}}">
      <input type="text"  value="{{i.About_me_name}}">
      <input type="mail" value="{{i.About_me_mail}}">
      <input type="text"  value="{{i.About_me_text}}"> <br>
{% endfor %}
</center>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html>
{% load static %}
<meta charset="UTF-8">
<title>Student Management</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href={% static "css/w3.css" %}>
<link rel="stylesheet" href={% static "fonts/Raleway/Raleway-Regular.ttf" %}>
<link rel="stylesheet" href={% static "font-awesome-4.7.0/css/font-awesome.min.css" %}>
<head>
<style>
body {

            width: 100%;
            height: 100%;
            max-height: 100%;
            margin: 0;
            padding: 0;
            background-image: url('static/images/nri.jpg');
            background-size:auto auto;
            background-repeat: no-repeat;
            background-size:cover;
        }
#entry {
    
	 

    height: 650px;
     padding: 100px 0 0 0; 
     
     
}
/* Full-width input fields */
input[type=text], input[type=password] {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    box-sizing: border-box;
}

/* Set a style for all buttons */
button {
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    cursor: pointer;
    width: 100%;
}

button:hover {
    opacity: 0.8;
}

/* Extra styles for the cancel button */
.cancelbtn {
    width: auto;
    padding: 10px 18px;
    background-color: #f44336;
}

/* Center the image and position the close button */
.imgcontainer {
    text-align: center;
    margin: 24px 0 15px 0;
    position: relative;
}

img.avatar {
    width: 40%;
    border-radius: 70%;
}

.container {
    padding: 16px;
}

span.psw {
    float: right;
    padding-top: 16px;
}

/* The Modal (background) */
.modal {
    
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /* Full height */
    overflow: auto; /* Enable scroll if needed */
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
    padding-top: 60px;
}

/* Modal Content/Box */


    .modal-content {
        background-color: #fefefe;
        margin: auto auto auto auto; /* 5% from the top, 15% from the bottom and centered */
        border: 1px solid #888;
        width: 30%; /* Could be more or less, depending on screen size */

        }
    
   @media screen and (max-width: 1000px) {
    .modal-content {
        background-color: #fefefe;
        margin: auto auto auto auto; /* 5% from the top, 15% from the bottom and centered */
        border: 1px solid #888;
        width: 60%; /* Could be more or less, depending on screen size */

        }
    }

/* The Close Button (x) */
.close {
    position: absolute;
    right: 25px;
    top: 0;
    color: #000;
    font-size: 35px;
    font-weight: bold;
}

.close:hover,
.close:focus {
    color: red;
    cursor: pointer;
}

/* Add Zoom Animation */
.animate {
    -webkit-animation: animatezoom 0.6s;
    animation: animatezoom 0.6s
}

@-webkit-keyframes animatezoom {
    from {-webkit-transform: scale(0)} 
    to {-webkit-transform: scale(1)}
}
    
@keyframes animatezoom {
    from {transform: scale(0)} 
    to {transform: scale(1)}
}

/* Change styles for span and cancel button on extra small screens */
@media screen and (max-width: 300px) {
    span.psw {
       display: block;
       float: none;
    }
    .cancelbtn {
       width: 100%;
    }
}
</style>
<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body >



<div id="entry">
<center><a href="{% url 'student:index' %}"class="w3-button w3-blue w3-padding"><i class="fa fa-users fa-fw"></i>  !!Log In!!</a></center>
</div>
<div id="id01" class="modal">
    
  <form method="post" class="modal-content animate" action="{% url 'student:Login' %}" enctype="multipart/form-data">
    {% csrf_token %}
	
	<!-- {% if user_previous_time %} -->
	    <!-- <p style="color:red;"><strong><b>{{ user_previous_time }}</b></strong></p> -->
       <!-- <button id="logoutBtn" name="logoutBtn" class="w3-button w3-red"><a href="{% url 'polls:Logout' id=user.id %}"><b>Logout</b></a></button> -->
    <!-- {% endif %} -->
		
	{% if error_message %}
            <p style="color:red;"><strong><b>{{ error_message }}</b></strong></p>
    {% endif %}
    <div class="imgcontainer">
      <span onclick="document.getElementById('id01').style.display='none'" class="close" title="Close Modal">&times;</span>
      <img src={% static "images/nri_logo.jpeg" %} alt="Avatar" style="width:30%">
    </div>

    <div class="container">
      <label><b>Username</b></label>
      <input type="text" placeholder="Enter Username" name="username" required>

      <label><b>Password</b></label>
      <input type="password" placeholder="Enter Password" name="password" required>


	  <div><input type="submit" value="Login" name="action" style="width:100%;background-color: green;border: none;padding: 10px 18px;font-weight:bold;"></div>
      <!-- <input type="checkbox" checked="checked"> Remember me -->
    </div>

    <div class="container" style="background-color:#f1f1f1">
      <button type="button" onclick="document.getElementById('id01').style.display='none'" class="cancelbtn">Cancel</button>
      <!-- <span class="psw"> <a href="#">Forgot password?</a></span> -->
    </div>
  </form>
</div>
<footer class="w3-container">
  </br>
    <h4><a href="#">Student Management</a></h4>
  <div class="w3-bar w3-top" style="seaz-index:4">
  <span class="w3-bar-item w3-right"><button id="add" name="add" class="w3-button w3-brown"><b><a href="{% url 'student:add_stu1'  %}">Add Student ItSelf+</a></b></button></span>
  <span class="w3-bar-item w3-left"><button id="About" name="About" class="w3-button w3-brown"><b><a href="{% url 'student:About'  %}">About Me+</a></b></button></span>
  </div>
    
    

</footer>
</body>

</html>

templates/masterDashboard.html
<html>
{% load static %}

<title>Student Info</title>

<script src={% static "js/form_validations_marketing.js" %}></script>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href={% static "css/jquery.dataTables.min.css" %}>
<link rel="stylesheet" href={% static "css/w3.css" %}>
<link rel="stylesheet" href={% static "fonts/Raleway/Raleway-Regular.ttf" %}>
<link href={% static "font-awesome-4.7.0/css/font-awesome.min.css" %} rel="stylesheet">
<link rel="stylesheet" href={% static "css/jquery-confirm.min.css" %}>
<link href={% static "css/bootstrap.min.css" %} rel="stylesheet">
<script src={% static "js/jquery.min.js" %}></script>
<script src={% static "js/jquery.min.1.7.1.js" %}></script>
<script type="text/javascript" src={% static "js/jquery.dataTables.min.js" %} ></script>
<script type="text/javascript" src={% static "js/bootstrap.min.js" %} ></script>


<style>
table, th, td {
    border: 1px solid black;
    padding: 1%;
}
table {
    border-spacing: 15px;
}

/* The Modal (background) */


/* Modal Content */
.modal-content {
    background-color: #fefefe;
    margin: auto;
    padding: 2px;
    border: 1px solid #888;
    width: 82%;
}

/* The Close Button */
.close {
    color: #aaaaaa;
    float: right;
    font-size: 40px;
    font-weight: bold;
}

.close:hover,
.close:focus {
    color: #000;
    text-decoration: none;
    cursor: pointer;
}



</style>

<body class="w3-light-grey">



<script>
$(document).ready(function(){
    
    $('#enquiryTable').dataTable({
  aaSorting: [[1, 'dsc']]
});

});
</script>


<div class="w3-bar w3-top w3-khaki w3-large" >
 
 <span class="w3-bar-item w3-x"> <a href="{% url 'student:Logout' %}"><button id="homepage" name="homepage" class="w3-button w3-red"><b>Logout</b></button></a> </span>   
 <span class="w3-bar-item w3-right"><button id="add" name="add" class="w3-button w3-brown"><b><a href="{% url 'student:add_stu' %}">Add Student+</a></b></button></span>
 <span class="w3-bar-item w3-right"><button id="Contact" name="Contact" class="w3-button w3-brown"><b><a href="{% url 'student:show_contact' %}">Contact+</a></b></button></span>
 <span class="w3-bar-item w3-right"><button id="add" name="add" class="w3-button w3-brown"><a href="{% url 'student:download' %}"><b>Download Report</b></a></button></span>
 
 
</div>
<br/>
<br/>
<br/>
<br/>





<div class="w3-container w3-responsive">

{% if stu_list %}
<table class="table table-striped" id="enquiryTable">
<thead>
<tr>
  <th>Enrollment NO</th>
  <th>First Name</th>
  <th>Last Name</th>
    <th>Date Of Birth</th>
    <th>Gender</th>

  <th>Details</th>
  <th>Edit</th>
  <th>Delete</th>
  
 
</tr>
</thead>
<tbody>
{% for stu in stu_list %}
<tr>
    
    <td>{{ stu.stu_id }}</td>
    <td>{{ stu.stu_fname }}</td>
    <td>{{ stu.stu_lname }}</td>
    <td>{{ stu.stu_Day}}-{{stu.stu_Month}}-{{stu.stu_Year}}</td>
    <td>{{stu.stu_gender}}</td>

    <td><button type="button" class="btn  btn-success"  onclick="updateCostModal(stu_id='{{ stu.stu_id }}', 
    stu_fname ='{{ stu.stu_fname }}'+ ' ' + '{{ stu.stu_lname }}',
    stu_Day='{{ stu.stu_Day}}'+'-'+'{{stu.stu_Month}}'+'-'+'{{stu.stu_Year}}',stu_gender='{{stu.stu_gender}}',
     stu_room='{{stu.stu_room}}',stu_contact='{{ stu.stu_contact }}', stu_email='{{ stu.stu_email }}',
     COURSES='{{ stu.COURSES}}',stu_branch='{{ stu.stu_branch}}',
    Address='{{ stu.Address}}',City='{{ stu.City}}',Pin_Code='{{ stu.Pin_Code}}',State='{{ stu.State}}',
    Country='{{ stu.Country}}',);">View</button></td>
    
    <td><a href="{% url 'student:edit_stu' stu_id=stu.stu_id %}"><button type="button" class="btn  btn-success">Edit</button></a></td>
    
    <td><a href="{% url 'student:del_stu' stu_id=stu.stu_id %}" onclick="return confirm('Are you sure you want to delete this Student?');"><button type="button" class="btn  btn-success w3-red">Delete</button></a></td>


	
       
</tr>
{% endfor %}

</tbody>

</table>
{% else %}

  <p>No Student details are available</p>
{% endif %}	

</div>

<div id="updateCostModal" name="updateCostModal" class="modal" style="margin-left:120px;">

<!-- Modal content -->
 <div class="modal-content animate" id="updateCostModalContent" name="updateCostModalContent" >
  <span onclick="document.getElementById('updateCostModal').style.display='none'" class="close" title="Close Modal">&times;</span>
  <!------------------------------------------------------------------------------ -->

<form role="form" method="post" id="update_kit_form_id" class="w3-container w3-card-4 w3-light-grey w3-text-blue w3-margin" action="#" enctype="multipart/form-data"  >
        {% csrf_token %}
<!-- <form action="/action_page.php" class="w3-container w3-card-4 w3-light-grey w3-text-blue w3-margin"> -->
<h1 class="w3-center">Student Details</h1>



    <div class="w3-col" style="width:21%">
      <div class="w3-row-padding w3-section">
	  <label for="stu_id"> Enrollment NO :: </label>
      <b><input id="stu_id" name="stu_id" class="w3-input w3-border w3-grey" value="" type="text"   readonly=""></input></b>
    </div>

</div>

<div class="w3-col" style="width:30%">
  <div class="w3-row-padding w3-section">
<label for="stu_fname"> Full Name :: </label>
  <b><input id="stu_fname" name="stu_fname" class="w3-input w3-border w3-grey" value="" type="text"   readonly=""></input></b>
</div>
</div>

<div class="w3-col" style="width:22%">
  <div class="w3-row-padding w3-section">
<label for="stu_Day"> Date Of Birth :: </label>
  <b><input id="stu_Day" name="stu_Day" class="w3-input w3-border w3-grey" value="" type="text"   readonly=""></input></b>
</div>
</div>


<div class="w3-col" style="width:13%">
  <div class="w3-row-padding w3-section">
<label for="stu_gender"> Gender :: </label>
  <b><input id="stu_gender" name="stu_gender" class="w3-input w3-border w3-grey" value="" type="text"   readonly=""></input></b>
</div>
</div>


<div class="w3-col" style="width:16%">
  <div class="w3-row-padding w3-section">
<label for="stu_room"> Room No :: </label>
  <b><input id="stu_room" name="stu_room" class="w3-input w3-border w3-grey" value="" type="text"   readonly=""></input></b>
  </div>
  </div>

<div class="w3-col" style="width:20%">
  <div class="w3-row-padding w3-section">
<label for="stu_contact"> Mobile Number :: </label>
  <b><input id="stu_contact" name="stu_contact" class="w3-input w3-border w3-grey" value="" type="text"   readonly=""></input></b>
  </div>
  </div>
    

    <div class="w3-col" style="width:33%">
      <div class="w3-row-padding w3-section">
	  <label for="stu_email"> Email Id :: </label>
      <b><input id="stu_email" name="stu_email" class="w3-input w3-border w3-grey" value="" type="text"   readonly=""></input></b>
      </div>
      </div>

      <div class="w3-col" style="width:25%">
        <div class="w3-row-padding w3-section">
      <label for="COURSES"> Courses :: </label>
        <b><input id="COURSES" name="COURSES" class="w3-input w3-border w3-grey" value="" type="text"   readonly=""></input></b>
      </div>
  </div>
  
  
      <div class="w3-col" style="width:30%">
        <div class="w3-row-padding w3-section">
      <label for="stu_branch"> Branch :: </label>
        <b><input id="stu_branch" name="stu_branch" class="w3-input w3-border w3-grey" value="" type="text"   readonly=""></input></b>
      </div>
  </div>
  

    <div class="w3-col" style="width:40%">
      <div class="w3-row-padding w3-section">
	  <label for="Address"> Address :: </label>
      <b><input id="Address" name="Address" class="w3-input w3-border w3-grey" value="" type="text"   readonly=""></input></b>
    </div>
</div>
        

    <div class="w3-col" style="width:20%">
      <div class="w3-row-padding w3-section">
	  <label for="City"> City :: </label>
      <b><input id="City" name="City" class="w3-input w3-border w3-grey" value="" type="text"   readonly=""></input></b>
    </div>
</div>
   

    <div class="w3-col" style="width:20%">
      <div class="w3-row-padding w3-section">
	  <label for="State"> State :: </label>
      <b><input id="State" name="State" class="w3-input w3-border w3-grey" value="" type="text"   readonly=""></input></b>
    </div>
</div>

<div class="w3-col" style="width:15%">
  <div class="w3-row-padding w3-section">
<label for="Pin_Code">Pin Code:: </label>
  <b><input id="Pin_Code" name="Pin_Code" class="w3-input w3-border w3-grey" value="" type="text"   readonly=""></input></b>
</div>
</div>

        

    <div class="w3-col" style="width:16%">
      <div class="w3-row-padding w3-section">
	  <label for="Country"> Country:: </label>
      <b><input id="Country" name="Country" class="w3-input w3-border w3-grey" value="" type="text"   readonly=""></input></b>
    </div>
</div>
        





</form>
</div>
</div>







<script>

function updateCostModal(stu_id,stu_fname,stu_Day,stu_gender,stu_room ,stu_contact, stu_email,COURSES,stu_branch,Address,City,Pin_Code,State,Country,) {
               
    document.getElementById('updateCostModal').style.display='block';
    document.getElementById('stu_id').value = stu_id;
    document.getElementById('stu_fname').value = stu_fname;
    document.getElementById('stu_Day').value = stu_Day;
    document.getElementById('stu_gender').value = stu_gender;
    document.getElementById('stu_room').value = stu_room;
    document.getElementById('stu_contact').value = stu_contact;
    document.getElementById('stu_email').value = stu_email;
    document.getElementById('COURSES').value = COURSES;
    document.getElementById('stu_branch').value = stu_branch;
    document.getElementById('Address').value = Address;
    document.getElementById('City').value = City;
    document.getElementById('Pin_Code').value = Pin_Code;
    document.getElementById('State').value = State;
    document.getElementById('Country').value = Country;
    


      

    
}

</script>




</body>
</html>

templates/view_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>